<?php
//Enter your code here, enjoy!

$array = array(array("English", "en", "_(disambiguation)"),
array("German", "de", "_(Begriffskl%C3%A4rung)" ),
array("French", "fr","_(homonymie)" ),
array("Dutch", "nl","_(doorverwijspagina)" ),
array("Italian", "it", "_(disambigua)" ),
array("Spanish", "es","_(desambiguaci%C3%B3n)" ),
array("Russian", "ru", "_(%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F)" ),
array("Swedish", "sv", "_(olika_betydelser)"),
array("Polish", "pl", "_(ujednoznacznienie)"),
array("Waray-Waray", "war","" ),
array("Japanese", "ja", "_(%E6%9B%96%E6%98%A7%E3%81%95%E5%9B%9E%E9%81%BF)"),
array("Portuguese", "pt", "_(desambigua%C3%A7%C3%A3o)"),
array("Arabic", "ar", "_(%D8%AA%D9%88%D8%B6%D9%8A%D8%AD)"),
array("Chinese", "zh", "_(%E6%B6%88%E6%AD%A7%E4%B9%89%E9%A1%B5)"),
array("Ukrainian", "uk", "_(%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%BD%D1%8F)"),
array("Catalan", "ca", ""),
array("Norwegian (Bokm%C3%A5l)", "no", "_(andre_betydninger)"),
array("Finnish", "fi", "_(t%C3%A4smennyssivu)"),
array("Czech", "cs", "_(rozcestn%C3%ADk)"),
array("Hungarian", "hu", "_(egy%C3%A9rtelm%C5%B1s%C3%ADt%C5%91_lap)"),
array("Turkish", "tr", "_(anlam_ayr%C4%B1m%C4%B1)"),
array("Romanian", "ro", "_(dezambiguizare)"),
array("Swahili", "sw", ""),
array("Korean", "ko", "_(%EB%8F%99%EC%9D%8C%EC%9D%B4%EC%9D%98)"),
array("Kazakh", "kk", ""),
array("Vietnamese", "vi", "_(%C4%91%E1%BB%8Bnh_h%C6%B0%E1%BB%9Bng)"),
array("Danish", "da", ""),
array("Esperanto", "eo", ""),
array("Serbian", "sr", "_(%D0%B2%D0%B8%D1%88%D0%B5%D0%B7%D0%BD%D0%B0%D1%87%D0%BD%D0%B0_%D0%BE%D0%B4%D1%80%D0%B5%D0%B4%D0%BD%D0%B8%D1%86%D0%B0)"),
array("Indonesian", "id", "_(disambiguasi)"),
array("Lithuanian", "lt", ""),
array("Volap%C3%BCk", "vo", ""),
array("Slovak", "sk", ""),
array("Hebrew", "he", "_(%D7%A4%D7%99%D7%A8%D7%95%D7%A9%D7%95%D7%A0%D7%99%D7%9D)"),
array("Persian", "fa", "_(%D8%A7%D8%A8%D9%87%D8%A7%D9%85%E2%80%8C%D8%B2%D8%AF%D8%A7%DB%8C%DB%8C)"),
array("Bulgarian", "bg", "_(%D0%BF%D0%BE%D1%8F%D1%81%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5)"),
array("Slovene", "sl", "_(razlo%C4%8Ditev)"),
array("Basque", "eu", "_(argipena)"),
array("Lombard", "lmo", ""),
array("Estonian", "et", "_(t%C3%A4psustus)"),
array("Croatian", "hr", "_(razdvojba)"),
array("Newar / Nepal Bhasa", "new", ""),
array("Telugu", "te", ""),
array("Norwegian (Nynorsk)", "nn", "_(fleirtyding)"),
array("Thai", "th", "_(%E0%B9%81%E0%B8%81%E0%B9%89%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%81%E0%B8%B3%E0%B8%81%E0%B8%A7%E0%B8%A1)"),
array("Galician", "gl", "_(hom%C3%B3nimos)"),
array("Greek", "el", ""),
array("Cebuano", "ceb", "_(pagklaro)"),
array("Malay", "ms", ""),
array("Haitian", "ht", ""),
array("Bosnian", "bs", ""),
array("Bishnupriya Manipuri", "bpy", ""),
array("Luxembourgish", "lb", "_(Homonymie)"),
array("Georgian", "ka", ""),
array("Icelandic", "is", "_(a%C3%B0greining)"),
array("Albanian", "sq", "_(kthjellim)"),
array("Latin", "la", "_(discretiva)"),
array("Breton", "br", "_(dishe%C3%B1velout)"),
array("Hindi", "hi", "_(%E0%A4%AC%E0%A4%B9%E0%A5%81%E0%A4%B5%E0%A4%BF%E0%A4%95%E0%A4%B2%E0%A5%8D%E0%A4%AA%E0%A5%80)"),
array("Azerbaijani", "az", "_(d%C9%99qiql%C9%99%C5%9Fdirm%C9%99)"),
array("Bengali", "bn", "_(%E0%A6%A6%E0%A7%8D%E0%A6%AC%E0%A7%8D%E0%A6%AF%E0%A6%B0%E0%A7%8D%E0%A6%A5%E0%A6%A4%E0%A6%BE%20%E0%A6%A8%E0%A6%BF%E0%A6%B0%E0%A6%B8%E0%A6%A8)"),
array("Macedonian", "mk", ""),
array("Marathi", "mr", ""),
array("Serbo-Croatian", "sh", "_(razvrstavanje)"),
array("Tagalog", "tl", ""),
array("Welsh", "cy", "_(gwahaniaethu)"),
array("Ido", "io", "_(homonimo)"),
array("Piedmontese", "pms", ""),
array("Latvian", "lv", "_(noz%C4%ABmju_atdal%C4%AB%C5%A1ana)"),
array("Tamil", "ta", "_(%E0%AE%A4%E0%AF%8A%E0%AE%9F%E0%AE%B0%E0%AF%8D%E0%AE%AA%E0%AF%81%E0%AE%9F%E0%AF%88%E0%AE%AF_%E0%AE%AA%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AE%AE%E0%AF%8D)"),
array("Sundanese", "su", "_(disambiguasi)"),
array("Occitan", "oc", ""),
array("Javanese", "jv", "_(disambiguasi)"),
array("Neapolitan", "nap", ""),
array("Low Saxon", "nds", "_(Mehrd%C3%BCdig_Begreep)"),
array("Sicilian", "scn", ""),
array("Belarusian", "be", ""),
array("Asturian", "ast", "_(dixebra)"),
array("Kurdish", "ku", ""),
array("Walloon", "wa", ""),
array("Afrikaans", "af", "Ceres_(dubbelsinnig)"),
array("Aragonese", "an", "_(desambigaci%C3%B3n)"),
array("Ripuarian", "ksh", ""),
array("Silesian", "szl", "_(ujednoznacz%C5%84y%C5%84y)"),
array("West Frisian", "fy", ""),
array("North Frisian", "fro", ""),
array("Cantonese", "zh-yue", "_(%E6%90%9E%E6%B8%85%E6%A5%9A)"),
array("Urdu", "ur", ""),
array("Interlingua", "ia", ""),
array("Irish", "ga", ""),
array("Yiddish", "yi", ""),
array("Alemannic", "als", ""),
array("Armenian", "hy", "_(%D5%A1%D5%B5%D5%AC_%D5%AF%D5%AB%D6%80%D5%A1%D5%BC%D5%B8%D6%82%D5%B4%D5%B6%D5%A5%D6%80)"),
array("Amharic", "am", ""),
array("Aromanian", "roa-rup", ""),
array("Banyumasan", "map-bms", ""),
array("Bihari", "bh", ""),
array("Corsican", "co", ""),
array("Chuvash", "cv", ""),
array("Divehi", "dv", ""),
array("Dutch Low Saxon", "nds-nl", ""),
array("Faroese", "fo", ""),
array("Friulian", "fur", ""),
array("Gilaki", "glk", ""),
array("Gujarati", "gu", ""),
array("Ilokano", "ilo", ""),
array("Kannada", "kn", ""),
array("Kapampangan", "pam", ""),
array("Kashubian", "csb", ""),
array("Khmer", "km", ""),
array("Ligurian", "lij", ""),
array("Limburgish", "li", ""),
array("Malayalam", "ml", ""),
array("Manx", "gv", ""),
array("M%C4%81ori", "mi", ""),
array("Maltese", "mt", ""),
array("N%C4%81huatl", "nah", ""),
array("Nepali", "ne", ""),
array("Norman", "nrm", ""),
array("Northern Sami", "se", ""),
array("Novial", "nov", ""),
array("Quechua", "qu", ""),
array("Ossetian", "os", ""),
array("Pali", "pi", ""),
array("Pangasinan", "pag", ""),
array("Pashto", "ps", ""),
array("Pennsylvania German", "pdc", ""),
array("Romansh", "rm", ""),
array("Samogitian", "bat-smg", ""),
array("Sanskrit", "sa", ""),
array("Scottish Gaelic", "gd", ""),
array("Scots", "sco", ""),
array("Sardinian", "sc", ""),
array("Sinhalese", "si", ""),
array("Tajik", "tg", ""),
array("Tarantino","roa-tara", ""),
array("Tatar", "tt", ""),
array("Tongan", "to", ""),
array("Turkmen", "tk", ""),
array("Upper Sorbian", "hsb", ""),
array("Uzbek", "uz", ""),
array("Venetian", "vec", ""),
array("V%C3%B5ro", "fiu-vro", ""),
array("Wu", "wuu", ""),
array("West Flemish", "vls", ""),
array("Yoruba", "yo", ""),
array("Zazaki", "diq", ""),
array("Min Nan", "zh-min-nan", ""),
array("Classical Chinese", "ah-classical", ""), 
array("Franco-Proven%C3%A7al/Arpitan", "frp", ""),
array("Ladino", "lad", ""),
array("Bavarian", "bar", ""),
array("Central_Bicolano", "bcl", ""),
array("Cornish", "kw", ""),
array("Mongolian", "mn", ""),
array("Hawaiian", "haw", ""),
array("Anglo-Saxon", "ang", ""),
array("Lingala", "ln", ""),
array("Interlingue", "ie", ""),
array("Wolof", "wo", ""),
array("Tok Pisin", "tpi", ""),
array("Tahitian", "ty", ""),
array("Crimean Tatar", "crh", ""),
array("Lojban", "jbo", ""),
array("Aymara", "ay", ""),
array("Zealandic", "zea", ""),
array("Emilian-Romagnol", "eml", ""),
array("Kyrgyz", "ky", ""),
array("Igbo", "ig", ""),
array("Oriya", "or", ""),
array("Malagasy", "mg", ""),
array("Zamboanga Chavacano", "cbk-zam", ""),
array("Kongo", "kg", ""),
array("Syriac", "arc", ""),
array("Vlax Romani", "rmy", ""),
array("Guarani", "gn", ""),
array("Moldovan", "mo", ""),
array("Somali", "so", ""),
array("Kabyle", "kab", ""),
array("Kashmiri", "ks", ""),
array("Saterland Frisian", "stq", ""),
array("Chechen", "ce", ""),
array("Udmurt", "udm", ""),
array("Mazandarani", "mzn", ""),
array("Papiamentu", "pap", ""),
array("Old Church Slavonic", "cu", ""),
array("Sakha", "sah", ""),
array("Tetum", "tet", ""),
array("Sindhi", "sd", ""),
array("Lao", "lo", ""),
array("Bashkir", "ba", ""),
array("Punjabi", "pnb", ""),
array("Inuktitut", "iu", ""),
array("Nauruan", "na", ""),
array("Gothic", "got", ""),
array("Tibetan", "bo", ""),
array("Lower Sorbian", "dsb", ""),
array("Cherokee", "chr", ""),
array("Min Dong", "cdo", ""),
array("Hakka", "hak", ""),
array("Oromo", "om", ""),
array("Burmese", "my", ""),
array("Samoan" , "sm", ""),
array("Ewe", "ee", ""),
array("Picard", "pcd", ""),
array("Uyghur", "ug", ""),
array("Assamese", "as", ""),
array("Tigrinya", "ti", ""),
array("Avar", "av", ""),
array("Bambara", "bm", ""),
array("Zulu", "zu", ""),
array("Pontic", "pnt", ""),
array("Navajo", "nv", ""),
array("Cree", "cr", ""),
array("Norfolk", "pih", ""),
array("Swati", "ss", ""),
array("Venda", "ve", ""),
array("Bislama", "bi", ""),
array("Kinyarwanda", "rw", ""),
array("Chamorro", "ch", ""),
array("Egyptian Arabic", "arz", ""),
array("Xhosa", "xh", ""),
array("Greenlandic", "kl", ""),
array("Inupiak", "ik", ""),
array("Buginese", "bug", ""),
array("Dzongkha", "dz", ""),
array("Tsonga", "ts", ""),
array("Tswana", "tn", ""),
array("Komi", "kv", ""),
array("Tumbuka", "tum", ""),
array("Kalmyk", "xal", ""),
array("Sesotho", "st", ""),
array("Twi", "tw", ""),
array("Buryat (Russian)", "bxr", ""),
array("Akan", "ak", ""),
array("Abkhazian", "ab", ""),
array("Chichewa", "ny", ""),
array("Fijian", "fj", ""),
array("Lak", "lbe", ""),
array("Kikuyu", "ki", ""),
array("Zhuang", "za", ""),
array("Fula", "ff", ""),
array("Luganda", "lg", ""),
array("Shona", "sn", ""),
array("Hausa", "ha", ""),
array("Sango", "sg", ""),
array("Sichuan Yi", "ii", ""),
array("Choctaw", "cho", ""),
array("Kirundi", "rn", ""),
array("Marshallese", "mh", ""),
array("Cheyenne", "chy", ""),
array("Ndonga", "ng", ""),
array("Kuanyama", "kj", ""),
array("Hiri Motu", "ho", ""),
array("Muscogee", "mus", ""),
array("Kanuri", "kr", ""),
array("Herero", "hz", ""),
array("Moloko", "mwl", ""),
array("Punjabi", "pa", ""),
array("Mingrelian", "xmf", ""),
array("Lezgian", "lez", ""),
array("Champenoisian", "chm", ""));

?>
